Calcular volumen a partir de medidas
Comunitea/CMNT_00098_2017_JIM_addons pull request #6
Opened 2019-07-30 09:31 UTC by pablo-lp

Desarrollo para que se calcule el volumen (rectangular) que ocupa un producto a partir de sus medidas

2019-07-31 06:50 UTC, jesusVMayor requested changes

2019-07-31 06:50 UTC, jesusVMayor commented on js_addons/models/volumes.py
> +###########################
Aunque aquí no tiene mucha importancia, es importante en python 2 poner en la primera linea 
`# -*- coding: utf-8 -*-`

2019-07-31 06:50 UTC, jesusVMayor commented on js_addons/models/product.py
> +    @api.model
Para que funcione se tiene que llamar con algún registro, no debe de tener @api.model

2019-07-31 06:50 UTC, jesusVMayor commented on js_addons/models/product.py
>          self._set_variant_discontinued(vals);
Esta llamada está mal, la función recorre self.product_variant_ids y aquí self estará vacío.

2019-07-31 06:50 UTC, jesusVMayor commented on js_addons/models/product.py
> +            template.write(related_vals)
No entiendo por qué reescribes unos valores que ya se establecen en el create.

2019-07-31 06:50 UTC, jesusVMayor commented on js_addons/models/product.py
> +    @api.onchange('product_size_depth', 'product_size_width', 'product_size_height')
Es un campo función, el onchange no tiene sentido, sería un depends.

2019-07-31 06:50 UTC, jesusVMayor commented on js_addons/models/product.py
> +    volume = fields.Float(compute='_compute_volume', digits=(3,2), store=False, help="Computed volume of the product (cube formula) in m³")
Por qué se vuelven a crear todos los campos? Si el template tiene 1 campo, como los de size, las variantes también lo tendrán. El único que podría tener sentido es el de volume, si quieres que se calcule de manera diferente.

2019-07-31 06:50 UTC, jesusVMayor commented on js_addons/views/product.xml
> +            <xpath expr="//group[@name='group_lots_and_weight']" position="replace">
Es necesario sobreescribir todo el grupo? si algún módulo hereda esta vista y añade algún otro campo en esta parte lo estarías eliminando.

2019-07-31 07:12 UTC, pablo-lp commented on js_addons/models/product.py
> +            template.write(related_vals)
está copiado del módulo original "product" para cuando se crea un producto sin variantes estos valores se copien a la variante única

2019-07-31 07:16 UTC, pablo-lp commented on js_addons/models/product.py
>          self._set_variant_discontinued(vals);
Entiendo lo que me dices, pero en principio esto ya estaba probado e implementado ¿será que no es necesario?

2019-07-31 07:20 UTC, pablo-lp commented on js_addons/models/product.py
> +    @api.onchange('product_size_depth', 'product_size_width', 'product_size_height')
El depends no es necesario ya que al no guardarse siempre se recalcula, al tener el onchange se actualiza en cuanto cubres los campos necesarios, de otra forma hasta guardar no se actualiza

2019-07-31 07:27 UTC, pablo-lp commented on js_addons/models/product.py
> +    volume = fields.Float(compute='_compute_volume', digits=(3,2), store=False, help="Computed volume of the product (cube formula) in m³")
En principio no lo hice, pero no funcionaba bien, creo que todas las variantes cogían el mismo valor, pero pruebo de nuevo

2019-07-31 07:33 UTC, pablo-lp commented on js_addons/views/product.xml
> +            <xpath expr="//group[@name='group_lots_and_weight']" position="replace">
Voy a mirarlo

2019-07-31 07:50 UTC, pablo-lp commented on js_addons/models/product.py
>          self._set_variant_discontinued(vals);
Debí de hacer un cambio (mal hecho) de última hora porque no funciona bien! Lo cambio

2019-07-31 08:22 UTC, pablo-lp commented on js_addons/models/product.py
> +    @api.onchange('product_size_depth', 'product_size_width', 'product_size_height')
Claro! Ayer creo que no era mi día

2019-08-02 10:20 UTC, jesusVMayor requested changes

2019-08-02 10:20 UTC, jesusVMayor commented on js_addons/models/product.py
> +    volume = fields.Float(compute='_compute_volume', digits=(3,6), store=False, help="Computed volume of the product (cube formula) in m³")
Es necesario poner inverse=False para evitar que quede editable.

2019-08-06 12:21 UTC, merged